### Listar todas as tarefas
GET http://localhost:5000/api/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5000/api/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Estudar Node.js"
}

### Alterar o status de uma tarefa
PUT http://localhost:5000/api/tarefas/alterar/{id}70fbdf06-806c-4acd-b652-66143fc4c23f